version: '3.9'

services:
  postgres:
    image: postgres:14
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        ['CMD', 'pg_isready', '-U', '${POSTGRES_USER}', '-d', '${POSTGRES_DB}']
      interval: 3s
      timeout: 2s
      retries: 3

  server:
    build:
      context: server
      dockerfile: dev.Dockerfile
    env_file: .env
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    volumes:
      - ./server:/app
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
