version: '3.9'

services:
  client:
    build:
      context: client
    env_file:
      - .env
    ports:
      - '80:80'
      - 443:443
    volumes:
      - ./client:/app:delegated
    environment:
      - NODE_ENV=production
  server:
    build:
      context: server
      dockerfile: prod.Dockerfile
    env_file: .env
    volumes:
      - backend_data:/app:delegated
    ports:
      - ${PORT}:${PORT}
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  backend_data:
