// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Course struct {
	Code        string `json:"Code"`
	Name        string `json:"Name"`
	Credit      int    `json:"Credit"`
	Semester    int    `json:"Semester"`
	LecturerNip string `json:"LecturerNIP"`
}

type CourseInput struct {
	Code        string `json:"Code"`
	Name        string `json:"Name"`
	Credit      int    `json:"Credit"`
	Semester    int    `json:"Semester"`
	LecturerNip string `json:"LecturerNIP"`
}

type Enrollment struct {
	StudentNim string  `json:"StudentNIM"`
	CourseCode string  `json:"CourseCode"`
	Grade      float64 `json:"Grade"`
}

type EnrollmentInput struct {
	StudentNim string  `json:"StudentNIM"`
	CourseCode string  `json:"CourseCode"`
	Grade      float64 `json:"Grade"`
}

type Lecturer struct {
	Nip     string `json:"NIP"`
	Name    string `json:"Name"`
	Address string `json:"Address"`
}

type LecturerInput struct {
	Nip     string `json:"NIP"`
	Name    string `json:"Name"`
	Address string `json:"Address"`
}

type Student struct {
	Nim     string `json:"NIM"`
	Name    string `json:"Name"`
	Address string `json:"Address"`
}

type StudentInput struct {
	Nim     string `json:"NIM"`
	Name    string `json:"Name"`
	Address string `json:"Address"`
}
