// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Course struct {
	Code     string    `json:"Code"`
	Name     string    `json:"Name"`
	Credit   int       `json:"Credit"`
	Semester int       `json:"Semester"`
	Lecturer *Lecturer `json:"Lecturer"`
}

type CourseInput struct {
	Code     string `json:"Code"`
	Name     string `json:"Name"`
	Credit   int    `json:"Credit"`
	Semester int    `json:"Semester"`
	Lecturer string `json:"Lecturer"`
}

type Lecturer struct {
	Nip     string `json:"NIP"`
	Name    string `json:"Name"`
	Address string `json:"Address"`
}

type LecturerInput struct {
	Nip     string `json:"NIP"`
	Name    string `json:"Name"`
	Address string `json:"Address"`
}

type Student struct {
	Nim     string `json:"NIM"`
	Name    string `json:"Name"`
	Address string `json:"Address"`
}

type StudentCourse struct {
	Student *Student `json:"Student"`
	Course  *Course  `json:"Course"`
	Grade   int      `json:"Grade"`
}

type StudentCourseInput struct {
	Student string `json:"Student"`
	Course  string `json:"Course"`
	Grade   int    `json:"Grade"`
}

type StudentInput struct {
	Nim     string `json:"NIM"`
	Name    string `json:"Name"`
	Address string `json:"Address"`
}
